### ISSUE TITLE
Reset function is not working properly

### ISSUE THREAD

**Issue by PascuMarius** [amiq-consulting/yamm#4]
Hi,

I found out something is not working properly with the reset function.
The scenario is:
- create a static memory;
- allocate some buffers inside it;
- call the reset function;
- allocate more buffers inside the static memory
When you try to allocate other buffers with **RANDOM_FIT** after reset, it is possible to get into a null pointer because "**number_of_free_buffers**" contains the same value that it had before calling the reset function.

The easy fix that I found is to set this counters to default value after setting the buffer pointers to null in the **intern_reset** function.

Regards,
Marius

**Comment by amiq-consulting** [comment]
Hi Marius! 

Thank you for reporting this issue. 
Your suggested fix makes sense. When removing all buffers from the static buffers we also need to set the values to "number_of_free_buffers" to initial value.

Best regards!
